<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\OpenTrack.UI\OpenTrack.UI.csproj" />
    <ProjectReference Include="..\OpenTrack.Core\OpenTrack.Core.csproj" />
    <ProjectReference Include="..\OpenTrack.Infrastructure\OpenTrack.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

</Project>
